CXX=g++

CXXFLAGS=-Wall  -std=c++11

server1:server1.cpp
	-${CXX} $^ ${CXXFLAGS} -o $@
	-./$@ 192.168.88.110 8888
	-rm ./$@

server2:server2.cpp
	-${CXX} $^ ${CXXFLAGS} -o $@
	-./$@ 192.168.88.110 8888
	-rm ./$@

server3:server3.cpp
	-${CXX} $^ ${CXXFLAGS} -o $@
	-./$@ 192.168.88.110 8888
	-rm ./$@

server4:server4.cpp
	-${CXX} $^ ${CXXFLAGS} -o $@
	-./$@ 192.168.88.110 8888
	-rm ./$@

server_kick:server_kick.cpp
	-${CXX} $^ ${CXXFLAGS} -o $@
	-./$@ 192.168.88.110 8888
	-rm ./$@

