CXX:=g++

CXXFLAGS:=-Wall  -std=c++11 -lpthread

pthread_create:pthread_create.cpp
	-${CXX} $^ ${CXXFLAGS} -o $@
	-./$@ 
	-rm ./$@

pthread_heap:pthread_heap.cpp
	-${CXX} $^ ${CXXFLAGS} -o $@
	-./$@ 
	-rm ./$@

pthread_mul1:pthread_mul1.cpp
	-${CXX} $^ ${CXXFLAGS} -o $@
	-./$@ 
	-rm ./$@

pthread_mul2:pthread_mul2.cpp
	-${CXX} $^ ${CXXFLAGS} -o $@
	-./$@ 
	-rm ./$@

pthread_mul3:pthread_mul3.cpp
	-${CXX} $^ ${CXXFLAGS} -o $@
	-./$@ 
	-rm ./$@

