CXX=g++

CXXFLAGS=-Wall  -std=c++11

client1:client1.cpp
	-${CXX} $^ ${CXXFLAGS} -o $@
	-./$@ 192.168.88.110 8888
	-rm ./$@

client2:client2.cpp
	-${CXX} $^ ${CXXFLAGS} -o $@
	-./$@ 192.168.88.110 8888
	-rm ./$@

client3:client3.cpp
	-${CXX} $^ ${CXXFLAGS} -o $@
	-./$@ 192.168.88.110 8888
	-rm ./$@

client4:client4.cpp
	-${CXX} $^ ${CXXFLAGS} -o $@
	-./$@ 192.168.88.110 8888
	-rm ./$@

client_kick:client_kick.cpp
	-${CXX} $^ ${CXXFLAGS} -o $@
	-./$@ 192.168.88.110 8888
	-rm ./$@

baidu:baidu.cpp
	-${CXX} $^ ${CXXFLAGS} -o $@
	-./$@ 
	-rm ./$@